### ISSUE TITLE
로그인,회원가입API이슈

### ISSUE THREAD

**Issue by socow** [walking-sunset/selection-task#10]
# 로그인,회원가입API 오류
안녕하세요 !! 고생이 많으십니다
회원가입이랑 로그인에서 보낸 api에서 응답이 오지않아서 문의드립니다
https로 변경해서도 시도해봤으나 같은 응답이 재대로 오지않습니다
# 에러메세지 및 이미지
<img width="590" alt="스크린샷 2022-10-05 오후 10 25 58" src="https://user-images.githubusercontent.com/105201721/194071682-681ea901-7ac6-4693-9c41-dd949c12410d.png">
<img width="568" alt="스크린샷 2022-10-05 오후 10 30 14" src="https://user-images.githubusercontent.com/105201721/194072574-b39566c3-2abe-4c42-8a50-0d49c617a732.png">

**Comment by choi2021** [comment]
저도 안되서 많이 당황했었는데 https://pre-onboarding-selection-task.shop/여기로 API주소가 바뀌었어요!

**Comment by walking-sunset** [comment]
안녕하세요, HTTPS 지원 및 사용하기 편한 도메인을 위해서 배포 주소가 변경되었습니다~! 변경된 주소 사용하시면 됩니다!
