### ISSUE TITLE
라이브러리 사용에 대해 문의드립니다.

### ISSUE THREAD

**Issue by movie42** [walking-sunset/selection-task#11]
## 라이브러리 사용에 대해 문의드립니다. 

1. React Router는 npm install react-router-dom이 맞나요? 
2. CRA에서 절대 경로를 사용하기 위해서 [react-app-rewired](https://github.com/timarney/react-app-rewired)를 설치해서 사용해도 되는지 문의드립니다.

**Comment by walking-sunset** [comment]
1. 맞습니다~!
2. 기능과 관련된 라이브러리가 아니라고 판단됩니다. 따라서 사용 가능합니다! :)
