### ISSUE TITLE
회원가입 기능 개발 문의

### ISSUE THREAD

**Issue by limdoohee** [walking-sunset/selection-task#12]
회원가입 기능은 제출시 API 에서 응답데이터를 받아서 어디까지 처리를 해야하는지,
로그인 할때는 회원가입한 계정으로만 해야하는건지 등
전반적인 회원가입 기능 개발 요구사항에 대해 설명 부탁드립니다

**Comment by walking-sunset** [comment]
- 어떤 부분이 궁금하신지 질문만으로는 제대로 파악이 안되네요, 요구사항에 적힌대로, 입력폼, 유효성 검사가 구현되어있으면 되고 API의 응답값에 따라 일반적인 회원가입 과정을 처리하면 됩니다.
- 회원가입을 하지 않으면 로그인을 하지 못하지 않을까요?
