### ISSUE TITLE
회원가입 이후 응답값 토큰

### ISSUE THREAD

**Issue by crystal993** [walking-sunset/selection-task#17]
안녕하세요~
회원가입 하면 응답값으로 access-token을 주는데, 
회원가입 이후에 access-token을 바로 로컬스토리지에 저장해서 로그인 된 것처럼 /todo  로 이동해야 되는 건가요??

**Comment by walking-sunset** [comment]
해당 부분에 대한 처리는 따로 요구사항에 없으며, 지원자님께서 자유롭게 판단하시면 됩니다.
1. 회원가입 후 바로 로그인 처리
2 회원가입 후 로그인페이지로 이동, 그 후 로그인
이 중 어떤 플로우로 구성하셔도 됩니다.
