### ISSUE TITLE
yarn berry 사용해도 되나요?

### ISSUE THREAD

**Issue by pongdang** [walking-sunset/selection-task#18]
안녕하세요!
yarn berry v3를 사용하고 싶은데 혹시 사용해도 될까요?!

**Comment by walking-sunset** [comment]
- 안녕하세요, 과제의 규모가 크지 않아서 yarn berry를 반드시 도입할 필요는 없을 것 같네요
- 별도의 yarn 설치과정 없이 실행가능하게 하기 위해서 yarn berry 사용은 지양해주시면 감사하겠습니다(일반적인 node_modules를 사용하는 yarn classic은 사용 가능합니다) :)
