### ISSUE TITLE
회원 가입/로그인 관련 질문 및 전역 상태관리 라이브러리 사용 가능 여부 

### ISSUE THREAD

**Issue by ericagong** [walking-sunset/selection-task#19]
안녕하세요. 선발 과제를 진행하는 도중 의문이 생긴 부분에 대해 질문드립니다. 

### 회원 가입 관련 질문
1. 회원 가입 시 `/auth/signup` 응답으로 받는 access_token 값도 로그인 시와 마찬가지로 로컬 스토리지에 바로 저장하면 되나요? 
1-1. 로컬 스토리지에 바로 저장한다면, 이후 바로 /todo로 리다이렉트 해야하는 건가요? 
1-2. 로컬스토리지에 저장하지 않는다면, 로그인 화면으로 전환해야 하는 건가요?

2. 회원 가입 시 `/auth/signup` 응답으로 서버측 에러메시지를 받는 경우, (예_이미 존재하는 이메일입니다.) 프론트 화면에 보여주어야 하나요? 보여주는 형태는 자유인지 궁금합니다. 

### 로그인 관련 질문
3. 로그인 시에도 회원가입시와 마찬가지로 이메일, 비밀번호에 대한 유효성 검사가 필요한 것 맞나요?

4. 로그인 시 `/auth/signin` 응답으로 서버측 에러메시지를 받는 경우, (예_unauthorized) 프론트 화면에 보여주어야 하나요? 보여주는 형태는 자유인지 궁금합니다. 

### todo 관련 질문
5. todo CRUD를 구현하는 과정에서 전역 상태관리 라이브러리를 사용해도 되나요? 
5-1. 전역 상태관리 라이브러리를 사용해도 된다면, react-redux, redux-toolkit 이 외에도 다른 라이브러리 중 원하는 것을 자유롭게 선택 사용할 수 있나요? 사용 불가하지 않은 전역 관리 라이브러리를 안내해주시면 좋을 것 같습니다. 
5-2. 전역 상태관리 라이브러리 중 react 내장 라이브러리인 contextAPI만 사용 가능한 건가요?

늦은 시간에 질문드려 죄송합니다.
내일도 편안한 하루 되시길 바랍니다. 감사합니다 😄

**Comment by walking-sunset** [comment]
### 회원 가입 관련 질문
1. 회원 가입 시 `/auth/signup` 응답으로 받는 access_token 값도 로그인 시와 마찬가지로 로컬 스토리지에 바로 저장하면 되나요? 
- 이부분은 따로 명세로 제한해두지 않았기에 지원자님의 판단대로 진행해주시면 됩니다. 기입해주신 두 플로우 모두 가능합니다.

2. 회원 가입 시 `/auth/signup` 응답으로 서버측 에러메시지를 받는 경우, (예_이미 존재하는 이메일입니다.) 프론트 화면에 보여주어야 하나요? 보여주는 형태는 자유인지 궁금합니다. 
- 예외상황에 대해서는 처리해주시는게 좋습니다. 처리의 형태는 자유입니다.

### 로그인 관련 질문
3. 로그인 시에도 회원가입시와 마찬가지로 이메일, 비밀번호에 대한 유효성 검사가 필요한 것 맞나요?
- 네, 맞습니다.

4. 로그인 시 `/auth/signin` 응답으로 서버측 에러메시지를 받는 경우, (예_unauthorized) 프론트 화면에 보여주어야 하나요? 보여주는 형태는 자유인지 궁금합니다. 
- 1-2의 답변과 동일합니다.

### todo 관련 질문
5. todo CRUD를 구현하는 과정에서 전역 상태관리 라이브러리를 사용해도 되나요?
- README.md에 기입된 내용대로 기능에 관련된 라이브러리는 사용이 불가능합니다. 따라서, 전역 상태관리 라이브러리의 사용은 제한됩니다. contextAPI의 경우 리액트의 내장 훅이기에, 이를 이용해 전역 상태 관리 형태로 사용하는 것은 가능합니다.

---

추가질문 있으시면 부담없이 이슈로 남겨주셔도 됩니다 :) 과제 화이팅하세요 💪
