### ISSUE TITLE
서버 에러 문의

### ISSUE THREAD

**Issue by borntok** [walking-sunset/selection-task#2]
createTodo api를 요청하면 `POST http://localhost:3000/todos 500 (Internal Server Error)` 에러가 발생해서 서버를 확인해보니

[Nest] 19652  - 2022. 08. 12. 오후 12:04:26   ERROR [ExceptionsHandler] SQLITE_CONSTRAINT: NOT NULL constraint failed: todo.userId
QueryFailedError: SQLITE_CONSTRAINT: NOT NULL constraint failed: todo.userId
    at Statement.handler (C:\Users\LGE1\wanted-pre-onboarding-fe\selection-task-master\src\driver\sqlite\SqliteQueryRunner.ts:113:26)
{ userId: undefined, email: '1234@1234.com' }
라는 에러 문구가 뜹니다. 이런 경우 어떻게 해야 하나요?ㅠㅠ

**Comment by borntok** [comment]
로컬서버 이용안하고 api 주소 사용했더니 해결되었습니다!

**Comment by walking-sunset** [comment]
안녕하세요 :)

요청할 때 사용하신 JWT가 어떻게 될까요??
만약 로컬 서버에서 회원가입을 하고 그 JWT를 API에서 사용했을 경우, API에 연결된 DB에 해당 유저에 대한 정보가 없어서 userId가 표시안될 수 있습니다. 이 부분 한번 확인해주세요!

요청의 payload와 headers등에 대한 정보를 제공해주시면 좀 더 상세하게 원인을 파악해드릴 수 있습니다.

**Comment by borntok** [comment]
로컬서버 재설치 후 회원가입했으며
사용한 JWT는 `eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFiY0BhYmMuY29tIiwiaWF0IjoxNjYwMzY0MDExLCJleHAiOjE2NjA5Njg4MTF9.Ii2qg-aLLm_7ABCeaSeqjHkZC5Uc7Xt1U8oVvPP49XA` 입니다..!

signup 요청을 했을 때
`Request URL: http://localhost:3000/auth/signup
Request Method: POST
Status Code: 201 Created
Remote Address: 127.0.0.1:3000
Referrer Policy: strict-origin-when-cross-origin
Access-Control-Allow-Headers: *
Access-Control-Allow-Methods: *
access-control-allow-origin: *
connection: close
content-length: 187
content-type: application/json; charset=utf-8
date: Sat, 13 Aug 2022 04:12:41 GMT
etag: W/"bb-HfJuQsP4NY36B9Ql1fdGkHsw4r0"
Vary: Accept-Encoding
x-powered-by: Express
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: ko-KR,ko;q=0.9,en-US;q=0.8,en;q=0.7
Connection: keep-alive
Content-Length: 45
Content-Type: application/json
Host: localhost:3000
Origin: http://localhost:3000
Referer: http://localhost:3000/
sec-ch-ua: "Chromium";v="104", " Not A;Brand";v="99", "Google Chrome";v="104"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/104.0.0.0 Safari/537.36`

`{email: "abc@abc.com", password: "12345678"}
email: "abc@abc.com"
password: "12345678"`
입니다..!

**Comment by walking-sunset** [comment]
해당 JWT를 해독해보니 원래 있어야 하는 userId에 대한 정보가 없고, email에 대한 정보만 들어있네요!
lcoal server말고, 배포된 서버를 이용해서 회원가입 - 회원가입시 응답받은 JWT를 이용해 createTodo의 과정까지 모두 시도해봐주세요~~!!
해당 과정에서 문제가 발생 시 마찬가지로 request에 대한 정보와 response에 대한 정보를 함께 알려주세요~!

**Comment by borntok** [comment]
배포된 서버를 이용해서 회원가입을 했는데

`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNzc0Bzc3MuY29tIiwiaWF0IjoxNjYwNDUyNTQ2LCJleHAiOjE2NjEwNTczNDZ9.pTWfjbHdV3Lw-6Lj71y6KWZgH2z3w-I1uZo5QHAeXzc`

**Header**

**Comment by walking-sunset** [comment]
- 확인결과 signin API 과정에서 userId가 누락되는 케이스가 있어 해당 부분 코드 수정해서 조치했습니다.
- 제보 감사드립니다 :) 해당 이슈 클로즈 하겠습니다. 혹시 동일한 상황 다시 발생하는 경우 Re-Open 해주세요 :)
