### ISSUE TITLE
질문드립니다

### ISSUE THREAD

**Issue by bitnaleeeee** [walking-sunset/selection-task#20]
안녕하세요
원티드 프로온보딩 지원자 이빛나라고 합니다.
다름이 아니라 resipotory 명을 [wanted-pre-onboarding-fe-7](https://github.com/bitnaleeeee/wanted-pre-onboarding-fe-7)
로 해서 12일에  제출을 하였는데,안내글에  resipotory 명을 wanted-pre-onboarding 로 작성하라고 변경되어 있어, 
혹시  다시 제출 해야하는지 아니면 다른 방법이 있을지해서 질의 드립니다..!

감사합니다

**Comment by walking-sunset** [comment]
안녕하세요, 기존 제출하신 링크는 그대로 유지하셔도 됩니다~!

**Comment by bitnaleeeee** [comment]
> 

감사합니다!
