### ISSUE TITLE
wanted-pre-onboarding-frontend 레포지토리 안에 폴더로 제출

### ISSUE THREAD

**Issue by dgd03146** [walking-sunset/selection-task#21]
wanted-pre-onboarding-frontend 레포지토리 안에 wanted-pre-onboarding-fe-7 폴더(cra로 만든 폴더)에 코드가 작성되어 있는 상태로 제출하였는데 괜찮나요? 리드미는 둘다 작성해놓았습니다.

**Comment by walking-sunset** [comment]
네 가능합니다. 해당 부분이 신경쓰이신다면 레파지토리 들어가면 바로 보이는 리드미에 소스코드 위치 설명해주세면 될 것 같아요~!
