### ISSUE TITLE
안녕하세요 프리온보딩 과제 제출관련 문의드립니다.

### ISSUE THREAD

**Issue by Debonchocola** [walking-sunset/selection-task#22]
안녕하세요 제가 12일에 시연영상과 함께 사전과제 제출을 했습니다.
배포를 해보고 싶어서 배포를 하여 일요일에 github에 올려두었습니다. 다시 제출을 하고 싶었지만 
이미 제출한 상태여서 제출하기 버튼을 누를 수 없었는데 혹시 수정된 날짜 기준인 일요일에 제출한 것으로 바꿔서 과제 평가를 받을 수 있는지 
문의드립니다.

**Comment by walking-sunset** [comment]
네, 가능합니다. 깃헙에 수정된 사항이 올라가있다면 해당 내용 기준으로 평가됩니다 :)
