### ISSUE TITLE
프로젝트 README.md 내용

### ISSUE THREAD

**Issue by hongseonga** [walking-sunset/selection-task#23]
readme파일에 프로젝트의 실행 방법을 기재해달라고 나와있는데 프로젝트의 실행방법이라는 건 말그대로 프로젝트 실행을 어떻게 하는지 설명하면 되는건가요? 
-> 예를 들면 회원가입을 한다 -> 로그인을 한다. 이런 식인건가요?

**Comment by walking-sunset** [comment]
실행방법은 프로젝트를 실행하기 위해서 어떤 환경이 구성되어있어야 하는지 등에 대한 안내(node version 등), 환경 변수, 패키지 설치, 실행 스크립트 등에 대한 설명을 의미합니다. 물론 말씀하신 실행 후 프로젝트의 기능을 어떻게 테스트할 수 있는지에 대한 내용도 포함되어 있으면 좋습니다(어떻게 회원가입 하고 로그인하고 투두리스트 사용하는 지 등에 대한 내용)
