### ISSUE TITLE
API 에러

### ISSUE THREAD

**Issue by HoyeonM** [walking-sunset/selection-task#24]
링크를 통해 직접 오픈, 로컬서버 구동 두가지 방법 모두 시도하였는데 
{"statusCode":404,"message":"Cannot GET /","error":"Not Found"} 에러가 뜨네요 ㅜ..

**Comment by walking-sunset** [comment]
API 호출에 대한 문제는 이렇게 단편적인 정보만으로는 도움을 드리기 어렵습니다. Request, Response에 대한 정보를 모두 함께 주셔야 상황을 파악할 수 있습니다. 다만 이 문제 같은 경우에는 주어진 정보로 판단해보면 요청하신 엔드포인트의 문제로 보이네요, README의 API 챕터 확인 하시고 기재된 엔드포인트 참고하셔서 구현하면 되실 것 같습니다~!
