### ISSUE TITLE
타입스크립트, Next.js 사용가능 여부 질문드립니다.

### ISSUE THREAD

**Issue by SJ0826** [walking-sunset/selection-task#25]
안녕하세요.

이번에 진행되는 사전과제에 타입스크립트와 Next.js를 사용해도 되는지 궁금합니다.

사용해서 진행해도 될까요?

**Comment by walking-sunset** [comment]
안녕하세요, 타입스크립트는 사용 가능하며, 환경구성은 README에 기재된대로 CRA 기준으로 진행해주시면 됩니다~!

**Comment by SJ0826** [comment]
네 감사합니다
