### ISSUE TITLE
응답예시 질문

### ISSUE THREAD

**Issue by ShineTiger** [walking-sunset/selection-task#26]
~https://github.com/walking-sunset/selection-task#2-3-updatetodo
URL을 /todos/:id 형식으로 요청하면 응답 예시로 userId가 2로 변경된것을 확인할 수 있습니다.
그렇다면 한번 더 같은 형식으로 요청을 하면 예시 안의 userId가 3으로 올라가나요? 
userId는 수정 횟수를 의미하는 데이터인지 궁금합니다~
해결했습니다!

**Comment by ShineTiger** [comment]
응답 예시를 보면 'id' 라고 된 이름이 있습니다. 
응답 예시만 보았을 때는 **내가 만든 todo의 갯수에 한해서** id 값이 늘어나는줄 알았는데요( 예: todo의 갯수가 1개면 id가 1, 2개면 2)
로직을 짜기전 먼저 요청 값으로 id를 직접 받아보니 천번대의 숫자가 같이 왔습니다. 아무래도 다른사람이 만든 모든 todo인것 같은데.. 이 부분은 무시하고  **내가 만든 todo의 갯수에 한해서** id 값이 늘어나는것으로 진행하면 되는걸까요? 
혹시나 하는 마음에 질문을 드립니다

**Comment by walking-sunset** [comment]
👍
