### ISSUE TITLE
서버 에러 문의

### ISSUE THREAD

**Issue by mandarin-sep** [walking-sunset/selection-task#27]
DeleteTodo 와  updateTodo api 적용시에 

"Request failed with status code 500" 에러가 발생합니다. 

로컬 서버와 배포된 서버 모두에서 동일한 증상이 발생하고 id 를 직접 넣어주고 명령을 실행해도 같은 증상이 발생합니다.

이 증상이 제게 문제가 있는건지 서버쪽에 문제가 있는건지 확인하고 싶습니다.

사용된 jwt는

eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEyMzEyM0BuYXZlci5jb20iLCJzdWIiOjE0ODMsImlhdCI6MTY3MDY5MDE4NiwiZXhwIjoxNjcxMjk0OTg2fQ.ZYEn9Ukhb8ax37hapPB8dn-a2fXFl1Rh2dbyKQSc6KY

이고 

에러 내용은 다음과 같습니다.
--
AxiosError {message: 'Request failed with status code 500', name: 'AxiosError', code: 'ERR_BAD_RESPONSE', config: {…}, request: XMLHttpRequest, …}
code
: 
"ERR_BAD_RESPONSE"
config
: 
adapter
: 
(2) ['xhr', 'http']
data
: 
"{\"todo\":\"hello world\",\"isCompleted\":true}"
env
: 
{FormData: ƒ, Blob: ƒ}
headers
: 
AxiosHeaders
Accept
: 
"application/json, text/plain, */*"
Authorization
: 
"Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjEyMzEyM0BuYXZlci5jb20iLCJzdWIiOjE0ODMsImlhdCI6MTY3MDY5MDE4NiwiZXhwIjoxNjcxMjk0OTg2fQ.ZYEn9Ukhb8ax37hapPB8dn-a2fXFl1Rh2dbyKQSc6KY"
Content-Type
: 
"application/json"
Symbol(Symbol.toStringTag)
: 
(...)
[[Prototype]]
: 
Object
maxBodyLength
: 
-1
maxContentLength
: 
-1
method
: 
"put"
timeout
: 
0
transformRequest
: 
[ƒ]
transformResponse
: 
[ƒ]
transitional
: 
{silentJSONParsing: true, forcedJSONParsing: true, clarifyTimeoutError: false}
url
: 
"https://pre-onboarding-selection-task.shop/todos/:4021"
validateStatus
: 
ƒ validateStatus(status)
xsrfCookieName
: 
"XSRF-TOKEN"
xsrfHeaderName
: 
"X-XSRF-TOKEN"
[[Prototype]]
: 
Object
message
: 
"Request failed with status code 500"
name
: 
"AxiosError"
request
: 
XMLHttpRequest
onabort
: 
ƒ handleAbort()
onerror
: 
ƒ handleError()
onload
: 
null
onloadend
: 
ƒ onloadend()
onloadstart
: 
null
onprogress
: 
null
onreadystatechange
: 
null
ontimeout
: 
ƒ handleTimeout()
readyState
: 
4
response
: 
"{\"statusCode\":500,\"message\":\"Internal server error\"}"
responseText
: 
"{\"statusCode\":500,\"message\":\"Internal server error\"}"
responseType
: 
""
responseURL
: 
"https://pre-onboarding-selection-task.shop/todos/:4021"
responseXML
: 
null
status
: 
500
statusText
: 
"Internal Server Error"
timeout
: 
0
upload
: 
XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}
withCredentials
: 
false
[[Prototype]]
: 
XMLHttpRequest
response
: 
config
: 
{transitional: {…}, adapter: Array(2), transformRequest: Array(1), transformResponse: Array(1), timeout: 0, …}
data
: 
{statusCode: 500, message: 'Internal server error'}
headers
: 
AxiosHeaders {content-length: '52', content-type: 'application/json; charset=utf-8'}
request
: 
XMLHttpRequest
onabort
: 
ƒ handleAbort()
onerror
: 
ƒ handleError()
onload
: 
null
onloadend
: 
ƒ onloadend()
onloadstart
: 
null
onprogress
: 
null
onreadystatechange
: 
null
ontimeout
: 
ƒ handleTimeout()
readyState
: 
4
response
: 
"{\"statusCode\":500,\"message\":\"Internal server error\"}"
responseText
: 
"{\"statusCode\":500,\"message\":\"Internal server error\"}"
responseType
: 
""
responseURL
: 
"https://pre-onboarding-selection-task.shop/todos/:4021"
responseXML
: 
null
status
: 
500
statusText
: 
"Internal Server Error"
timeout
: 
0
upload
: 
XMLHttpRequestUpload {onloadstart: null, onprogress: null, onabort: null, onerror: null, onload: null, …}
withCredentials
: 
false
[[Prototype]]
: 
XMLHttpRequest
status
: 
500
statusText
: 
"Internal Server Error"

**Comment by walking-sunset** [comment]
안녕하세요, 요청을 API에서 의도한대로 하고 있지 않으신걸로 보입니다. 서버에서 상정하지 않은 상황이라서 500에러가 발생하는 것으로 보이네요. 어떤 부분이 잘못됬는지는 선발 과제이므로 아쉽게도 자세히 알려드리기 어렵습니다 :)
