### ISSUE TITLE
안녕하세요. 제출 시기에 따른 가산점에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by tnals545** [walking-sunset/selection-task#28]
11일까지 제출한다면 0.5점의 가산점을 받는다는 것을 확인하고 11일에 제 github 주소를 제출했습니다.

만약 이후에 제가 추가로 commit을 한다면 가산점은 받지 못하고 수정된 내용으로 채점이 될까요?

**Comment by walking-sunset** [comment]
만약 이후에 제가 추가로 commit을 한다면 가산점은 받지 못하고 수정된 내용으로 채점이 될까요? -> 네 맞습니다. 제출 이후의 커밋들은 반영하지 않습니다. 제출 이후에 추가로 수정해보고 싶은 요소가 있다면 별도의 브랜치에서 작업하시는 것을 추천드립니다 :)
