### ISSUE TITLE
안녕하세요! 과제 접수기간 문의드립니다!

### ISSUE THREAD

**Issue by kim-a-reum** [walking-sunset/selection-task#29]
안녕하세요! 프리온보딩 원티드 공고에 15일 24시, 5일 24시라고 다르게 표기되어있어 과제 제출 및 신청 가능 기간에 대하여 여쭤봅니다!
12월 15일 24시까지 과제 제출 및 온보딩 신청이 가능한가요 ?

**Comment by walking-sunset** [comment]
네 맞습니다 15일 24시까지 제출 가능합니다~!
