### ISSUE TITLE
제출시기 관련해서 질문남깁니다

### ISSUE THREAD

**Issue by LLSJYY** [walking-sunset/selection-task#30]
제가 최근커밋한것 으로  시점을 뒤로 미루고 싶은데 가능할까요? 
제출시기는 11일 23:50분정도 됩니다.  푸쉬하는 과정에서 read.me가 날라가서 .. 
제가 아래 이슈들을 확인 해보았는데 main 에 마지막까지 커밋한 시기로 채점되는거로 인지하고 있으면 될까요?

**Comment by walking-sunset** [comment]
네 확인했습니다~!, 채점 당시 최근 커밋 기준으로 채점됩니다!
