### ISSUE TITLE
delete 요청시 statusCode: 500, message: Internal server error

### ISSUE THREAD

**Issue by Sungrinhan** [walking-sunset/selection-task#33]
문제 : todo list 삭제요청 시 에러발생
에러내용 : {statusCode: 500, message: "Internal server error"}
엔드포인트: DELETE  /todos/:id  (https://pre-onboarding-selection-task.shop/todos/:604)

api 요청 시 500  에러로 무엇이 잘못되었는지 모르겠습니다. 확인 부탁드립니다.

**Comment by kimhw7** [comment]
저도 todo 수정 put 요청 시 500에러 발생합니다.

에러내용 : {statusCode: 500, message: "Internal server error"}
엔드포인트: PUT /todos/:id(https://pre-onboarding-selection-task.shop/todos/:534)

**Comment by Sungrinhan** [comment]
넹 저도 put요청시 같은 에러가 발생하네요

**Comment by younuk23** [comment]
URL에서 `:`라는 표현은 통상 path parameter를 표현할 때 사용됩니다. 그래서 `:id`는 `:604`로 요청을 보내는 것이 아닌 `https://pre-onboarding-selection-task.shop/todos/604`와 같이 id를 해당 자리에 넣어주라는 의미로 해석하시면 되겠습니다. 엔드포인트 수정해서 다시 요청 해보시면 될거에요 :)

**Comment by kimhw7** [comment]
: 빼고 하니 해결 됐습니다! 감사합니다 :)
