### ISSUE TITLE
회원가입 시 유효성 검사 질문

### ISSUE THREAD

**Issue by ggsno** [walking-sunset/selection-task#34]
안녕하세요! 유효성 검사 조건에 대해 궁금한 점이 있어서 질문 드립니다.
![image](https://user-images.githubusercontent.com/46833758/216730988-a265777a-91b8-4387-a9ce-2038c85fdcac.png)

혹시 회원가입 유효성 검사 시에 "비밀번호 확인" 조건도 새로운 조건으로 간주 돼 지양사항일까요?
![image](https://user-images.githubusercontent.com/46833758/216731211-1f524085-0163-47ac-8b01-01a4293f7d47.png)

**Comment by younuk23** [comment]
안녕하세요, 네 질문주신대로 비밀번호 확인도 새로운 조건으로 간주할 수 있을 것 같습니다. 비밀번호 확인 조건 없이 진행해주시면 되겠습니다 :)
