### ISSUE TITLE
input 태그 대신 textarea 태그를 사용해도 되나요?

### ISSUE THREAD

**Issue by foreknowledge** [walking-sunset/selection-task#35]
Todo 아이템을 수정할 때 `<input type="text">` 대신 `<textarea>`를 사용한다면 혹시 문제가 될까요?

**Comment by younuk23** [comment]
네. 큰 문제가 되지 않는다면, 가이드에 적힌대로 input tag를 사용하는 방향으로 진행해주시면 되겠습니다 :)
