### ISSUE TITLE
signup API 이슈 문의

### ISSUE THREAD

**Issue by woongminKi** [walking-sunset/selection-task#36]
안녕하세요. 과제를 진행하다 궁금한 것이 있어 문의드립니다.

Read.me API 명세 되어 있는 것 처럼 signup에서 url(https://pre-onboarding-selection-task.shop/auth/signup)에 post로 api를 쐈는데 400 error라고 나옵니다.
headers와 body에도 명세되어 있는 값을 함께 넣어 보냈는데도 400에러가 나옵니다. postman에도 쏴봤는데 똑같습니다.
제가 end point를 잘 못 잡고 있는걸까요? API는 잘 동작하고 있을까요?
확인 후 답변해주시면 감사하겠습니다.

<img width="515" alt="스크린샷 2023-02-05 오후 10 15 54" src="https://user-images.githubusercontent.com/96522144/216821153-e3949c39-15f3-42e5-95e6-9262c1cd65f1.png">

**Comment by younuk23** [comment]
안녕하세요, 현재 API는 정상동작 중입니다. API 호출을 보내는 형태에 문제가 있으신 것 같네요, 호출과정에서 문제가 생겼을 때 정확한 정보를 알기 위해서는 호출에 대한 내용 전문(Headers, Body 등)을 함께 첨부해주셔야 문제를 파악할 수 있습니다. 다만 질문자님께서 말씀하신 경우 통상 Headers를 잘못 설정하셔서 생기는 문제이니 이 부분을 한번 확인해보시면 좋을 것 같네요

수행능력을 평가하는 과제이기에 요청과정에서 어떤 부분을 잘못 처리했고 어떻게 해야하는지 정답을 정확히 말해드릴 수는 없는 점 이해바랍니다.
