### ISSUE TITLE
유효성검사 관련 질문드립니다.

### ISSUE THREAD

**Issue by Jeong-jj** [walking-sunset/selection-task#39]
유효성 검사 구현 부분에서 제한 조건외에 추가 조건은 지양한다고 되어있어서 궁금한 점이 있어서 질문 드립니다!

이메일 조건이 "**@포함**" 만이 조건이라면

1. **@만 단독**으로 있는 경우
2. @aaa.aa 와 같이 **email의 id파트가 빠져있는** 경우
3. ㅁㅁ@ㅁㅁㅁ 혹은 ㅁㅁ@ aaㅁ.aa 와 같이 **한글**이나 **공백**이 포함되는 경우
4. aa@&^&*!asd 와 같이 **@외의 특수 문자**들이 함께 포함되는 경우
5. aa@aa 와 같이 **.com, .net 등이 포함되지 않는** 경우

위 예시 모두 유효성 검사에서 pass되는 걸로 이해하면 되는 걸까요?

**Comment by younuk23** [comment]
네 맞습니다, 안내드린대로 "@"만 포함되면 조건을 충족하는 것으로 판단하시면 됩니다 :)

**Comment by Jeong-jj** [comment]
답변 감사합니다! :D
