### ISSUE TITLE
userId 문의

### ISSUE THREAD

**Issue by Gn0lee** [walking-sunset/selection-task#4]
todo안에 userId가 있는데 이것이 유의미한 데이터인지 궁금합니다.

로그인이나 회원가입 시 userId가 주어지지 않는것으로 보아 userId값에 상관없이 모든 todo를 렌더링 하면 되는 것이 맞는지 궁금합니다.

**Comment by walking-sunset** [comment]
안녕하세요.
정상적으로 회원가입 및 로그인이 된 상태라면 JWT안에 userId에 대한 정보가 포함되어 있고
투두리스트를 요청할 시 해당 userId를 이용해서 해당 유저의 투두리스트만 응답해주기에 응답값으로 온 모든 투두리스트는 해당 유저의 투두리스트입니다.
