### ISSUE TITLE
사이트 처음 들어오자마자 보이는 화면을 어떤 페이지를 보여줘야 하나요?!

### ISSUE THREAD

**Issue by hongsoom** [walking-sunset/selection-task#40]
```jsx
 {path: "/", element: <App /> },
 { index: true, element: <SignUpInForm /> },
 {
            path: '/signup',
            element: <SignUpInForm />,
},
```
따로 경로 설정하고  처음 들어올 때 회원가입 페이지를 먼저 보이도록 했는데 이렇게 보다는 '/' 페이지 따로 '/signup' 페이지 따로 하는게 맞는건가요?!

**Comment by younuk23** [comment]
안녕하세요, 첫 페이지는 어떤 페이지가 되어도 상관없습니다. 지원자분께서 자유롭게 설정해주시면 됩니다. 다만, 가이드에서 설명드린대로 signup , signin 경로에 각각 회원가입, 로그인 기능이 구현되어 있으면 됩니다 :)
