### ISSUE TITLE
로그인/회원가입

### ISSUE THREAD

**Issue by juhee067** [walking-sunset/selection-task#45]
회원가입에서 아이디 중복도 검사해야하나요?!

**Comment by walking-sunset** [comment]
아이디 중복을 검사하실 필요는 없습니다. 다만, 아이디가 중복 될 경우 서버에서 에러 응답을 줄 거라서 여기에 대해 적절한 에러처리를 해주시면 좋겠네요. 다만, 에러처리는 과제의 필수 요구사항은 아니기에 지원자님의 판단에 따라 진행해주시면 되겠습니다. :)
