### ISSUE TITLE
API 주소 링크

### ISSUE THREAD

**Issue by dev-seongjoo** [walking-sunset/selection-task#46]
API 주소 링크에 문제가 있는 거 아닌지 질문드립니다.

**Comment by walking-sunset** [comment]
SSL 인증서 관리 방식 변경으로 인해 API 주소가 https://pre-onboarding-selection-task.shop/ 에서 https://www.pre-onboarding-selection-task.shop/로 변경되었습니다. 해당부분 참고 후 작업 진행해주시면 되겠습니다, 이상 있을 시 문의주세요 :)

**Comment by dev-seongjoo** [comment]
해당 링크에 접속했을 때 
{"statusCode":404,"message":"Cannot GET /%EB%A1%9C","error":"Not Found"}
라고 뜨는데 이게 맞는 건가요,,,?

**Comment by walking-sunset** [comment]
https://www.pre-onboarding-selection-task.shop/ 뒤에 문서에 가이드 된 경로 넣어서 요청하시면 정상적으로 요청 이루어지는 것으로 확인됩니다. 통신이 안되신다면 요청과 응답에 대한 자세한 정보를 함께 주셔야지 어떤 부분이 문제인지 확인해드릴 수 있습니다.

**Comment by dev-seongjoo** [comment]
아 제가 이해를 잘못하고 있었네요 ! 감사합니다 !
