### ISSUE TITLE
제출 화면과 링크 관련하여 질문드립니다

### ISSUE THREAD

**Issue by Yena-Yun** [walking-sunset/selection-task#47]
안녕하세요, 과제 주의사항에 올바른 화면과 링크 제출에 관해 안내해주신 부분을 읽었습니다. <br/>
올려주신 server 코드를 클론 받고 <br/>
client 형태로 CRA를 만들었더니 다음과 같은 형태가 되었습니다.<br/>

![image](https://user-images.githubusercontent.com/68722179/229437146-3de51add-2c8c-4dba-8b3f-452fdf88a595.png)

이렇게 하면 레포 첫 화면에서 src 폴더가 보이지 않아서 <br/> 
주의사항에서 말씀하신 '올바른 화면'이 아니고,<br/> 
client 안에 들어가서 src가 보이는 화면의 링크는<br/> 
'올바르지 않은 링크'가 되는 것 같은데 어떤 형태로 제출을 해야 할지 잘 모르겠습니다!<br/>

**Comment by Yena-Yun** [comment]
생각해보니 서버 코드는 server 폴더에 모아 넣고 CRA 코드는 client 폴더에 넣지 않으면 되는 것 같아서 이슈는 닫았습니다 :)

**Comment by walking-sunset** [comment]
@Yena-Yun 네, 생각하신대로 진행해주시면 될 것 같습니다! 그리고, 이 레파지토리의 소스파일이 굳이 포함될 필요는 없기에 server 폴더는 제외하셔도 무방합니다 :)

**Comment by Yena-Yun** [comment]
아하 소스파일이 포함되지 않아도 괜찮군요~ 답변 감사합니다!
