### ISSUE TITLE
로컬 테스트 후 배포시 엔드포인트 질문

### ISSUE THREAD

**Issue by dev-seongjoo** [walking-sunset/selection-task#48]
백엔드 파일 다운 받아서 로컬 테스트할 때는 엔드 포인트를 http://localhost:8000/todos 이런 식으로 설정해놨다가 배포하려고 해서 앞에 주소 빼고 /todos 이렇게 수정했는데 이 상태로 배포해도 문제 없을까요?

**Comment by walking-sunset** [comment]
사전에 안내드린대로 배포된 환경에서 모든 기능이 정상 동작해야합니다. 만약 지원자분께서 배포한 환경에 접속했을 때 API와 상호작용을 비롯한 모든 동작이 정상적으로 이루어지지 않는다면 배포가 완료된 것으로 인정이 되지 않습니다 :)

**Comment by dev-seongjoo** [comment]
아 제가 이해를 잘못하고 있었네요 ! 감사합니다 !
