### ISSUE TITLE
eslint, prettier

### ISSUE THREAD

**Issue by ARONGLEE** [walking-sunset/selection-task#49]
eslint, prettier 적용해도 괜찮나요? 
그리고 npm이나 yarn 둘중에 아무거나 사용해도 괜찮은지 궁금합니다.

**Comment by walking-sunset** [comment]
- eslint, prettier 사용가능합니다. 
- 패키지매니저의 경우 문서에서 안내된 clone 이후 `npm install & npm start` 명령어를 통해서 실행이 된다는 전제하에 별도의 제한은 없습니다.

**Comment by ARONGLEE** [comment]
넵 감사합니다! :)
