### ISSUE TITLE
updateTodo에 관한 문의 입니다.

### ISSUE THREAD

**Issue by Dev-jwJeong** [walking-sunset/selection-task#5]
투두 리스트에 대한 수정을 할 때 todo와 isCompleted를 텍스트만 수정할 경우, 완료 여부만 수정할 경우로 따로 생각해야 하나요?

**Comment by walking-sunset** [comment]
- todo에 들어간 text와 isCompleted 여부 모두 수정 가능하게 만들어주시면 됩니다.
- 그 과정에서 두개를 한번에 처리할지, 나눠서 처리할지는 지원자분의 의도에 맞게 진행해주시면 됩니다 :)
