### ISSUE TITLE
gh-pages 배포할 때 HashRouter로 라우트해도 괜찮을까요?

### ISSUE THREAD

**Issue by youngentry** [walking-sunset/selection-task#50]
github.io/wanted-pre-onboarding-frontend/#/signin

위의 주소처럼 주소에 해시(#)/ 가 url에 포함되어 있어도 되는지 궁금합니다!

**Comment by younuk23** [comment]
문서에서 말씀드린대로 리다이렉트, 페이지 접근 등을 포함 모든 기능이 정상동작한다면 무관합니다 :)
