### ISSUE TITLE
타입스크립트 사용가능 여부 및 state 라이브러리

### ISSUE THREAD

**Issue by wjdrk70** [walking-sunset/selection-task#51]
타입스크립트를 사용하여도 괜찮습니까?
가이드라인대로 react-query 도 안되니 redux도 안되겠지요?
CRA 시 기본으로 탑재되어있는데 jest-dom 등 testing-library 는 사용해도 괜찮는거죠?

**Comment by younuk23** [comment]
네 react-query나 redux 같은 경우 기능 구현에 사용되는 라이브러리기에 사용이 불가능합니다.
typescript와 testing 라이브러리는 기능구현과 직접적인 연관이 없기에 사용 가능합니다 :)

**Comment by wjdrk70** [comment]
> 네 react-query나 redux 같은 경우 기능 구현에 사용되는 라이브러리기에 사용이 불가능합니다. typescript와 testing 라이브러리는 기능구현과 직접적인 연관이 없기에 사용 가능합니다 :)

네감사합니다!
