### ISSUE TITLE
data-testid 속성 관련하여 질문 드립니다.

### ISSUE THREAD

**Issue by jeongdopark** [walking-sunset/selection-task#52]
안녕하세요 
가이드 라인 data-testid 속성 관련하여 질문드립니다.
> 이메일 input에 data-testid="email-input" 속성을 부여해주세요
패스워드 input에 data-testid="password-input" 속성을 부여해주세요

/signup 페이지와 /signin 페이지에서 
이메일 input에는 data-testid="email-input" 속성을 부여하고
비밀번호 input에는 data-testid="password-input" 속성을 부여하는 게 맞을까요 ? 

/signin 하위 목차에 해당 요구사항이 명시 되어있어서, 혹시 /signin 페이지에만 해당하는 요구사항인지 싶어서 질문 드립니다.

**Comment by younuk23** [comment]
안녕하세요,
네, 이해하신대로 signup, signin 두 페이지 모두에서 input에 testid 속성을 부여해주시는게 맞습니다.
testid에 대한 요구사항이 signup 하위 목차에 명시되어 있어 혼동이 있는 부분은 수정하도록 하겠습니다. 피드백 감사드립니다 :)

**Comment by jeongdopark** [comment]
답변 감사합니다 :-)
