### ISSUE TITLE
안녕하세요 과제 진행중 문의드립니다.

### ISSUE THREAD

**Issue by tead1234** [walking-sunset/selection-task#53]
1. 서버와 api 통신을 진행하던 중 이틀 전까지는 통신이 잘되다가 최근엔 axioserror가 뜨는데요 혹시 서버에 과부하나 무슨 문제가 생긴건지 궁금합니다.
2.  과제 요구사항 중에 새로고침을 해도 추가된 todo가 사라지면 안된다고 적혀있는데요. state에 todo를 보관하면 필연적으로 초기화가 되므로 이 부분은 로컬스토리지를 활용해서 구현해도 되는 부분인가요?

**Comment by younuk23** [comment]
1. 통신에 관련된 문제는 요청과 응답에 대한 내용을 모두 함께 첨부해주셔야 문제를 파악할 수 있습니다. 확인결과 현재 서버상의 문제는 없습니다.
2. 서버 API와 연동한다면, 관련된 정보가 데이터베이스에 저장되고 불러올 수 있기에 로컬스토리지 없이 이를 활용하신다면 요구사항을 충족시킬 수 있을것으로 보입니다.

**Comment by tead1234** [comment]
> 안녕하세요,
> 
> 1. 통신에 관련된 문제는 요청과 응답에 대한 내용을 모두 함께 첨부해주셔야 문제를 파악할 수 있습니다. 확인결과 현재 서버상의 문제는 없습니다.
> 2. 서버 API와 연동한다면, 관련된 정보가 데이터베이스에 저장되고 불러올 수 있기에 로컬스토리지 없이 이를 활용하신다면 요구사항을 충족시킬 수 있을것으로 보입니다.

아이고 밑에 있는 db api를 못봤네요.. 감사합니다.
