### ISSUE TITLE
과제 구현 중 질문드립니다.

### ISSUE THREAD

**Issue by no-support** [walking-sunset/selection-task#54]
1. 채점 안내 사항에 보면 사전 과제 실험도에 따라 5점까지 부여하던데, 
각 점수의 기준을 알 수 있을까요?
스타일을 추가하는 것은 채점에 영향을 미치는지,
일단 모든 기능이 구현되면 5점인지, 아니면 모든 기능이 구현되었어도 리팩토링이 많이 필요한 경우
몇 점 감점이 되는지, 타입스크립트로 구현하면 가산 요소인지 등을 알고 싶습니다.

2. Assignment 7에 'TODO의 체크박스를 통해 완료 여부를 수정할 수 있도록 해주세요.' 라고 되어 있는데, 새로고침해도 체크박스가 수정된 상태로 보여야 하나요? 아니면 제출 버튼을 눌렀을 때만 새로고침했을 때 수정된 상태로 보이면 되나요?

3. 과제에 data- 속성을 몇몇 엘리먼트에 부여해야 되던데, 이유를 알 수 있을까요?

**Comment by walking-sunset** [comment]
1. 아쉽게도, 세부 채점 기준은 공개해 드릴 수 없습니다 :)

2. 체크박스를 수정하는 순간 즉시 완료 여부가 수정되는 방식으로 구현하시면 됩니다. 완료여부 수정에 별도의 제출버튼 등의 추가 액션은 필요하지 않습니다, 따라서 체크박스를 수정하고 새로고침을 하면 수정된 상태로 보여야 합니다.

3. 기능 구현이 정상적으로 되었는지 확인하는 과정에서 사용됩니다.
