### ISSUE TITLE
사전과제 제출 날짜 기준 질문

### ISSUE THREAD

**Issue by owel-dev** [walking-sunset/selection-task#55]
안녕하세요. 
사전과제 제출 시기 관련해서 질문이 있습니다.
<img width="727" alt="Screen Shot 2023-04-08 at 8 03 25 PM" src="https://user-images.githubusercontent.com/40191730/230717729-e2dccce0-ebd6-466c-bd78-a47fae542e26.png">
사전과제 제출 시기별 가산점 관련해서
**(~04.09)** 라는 문구는
4월 10일 00시 이전에 제출하면 된다는(4월 9일 11시 59분 제출분 유효) 의미인 건가요?

**Comment by walking-sunset** [comment]
안녕하세요.
네, 이해하신대로 4월 9일 24:00내에 제출이 되면 제출시기에 따른 가산점이 부여됩니다. :)
