### ISSUE TITLE
api 서버 문제인지 확인 부탁드립니다

### ISSUE THREAD

**Issue by mandarin-sep** [walking-sunset/selection-task#56]
api를 사용하는데 ERR_NAME_NOT_RESOLVED 라는 에러가 발생해서 제공된 api 서버 주소인 

https://pre-onboarding-selection-task.shop/ 에 직접 접속을 했더니 DNS_PROBE_FINISHED_NXDOMAIN 에러가 발생했습니다. 

해당 에러를 검색해보니까 저의 인터넷과 컴퓨터의 문제로 에러가 발생할 수 있다고 해서 

지인집에서 저의 소스 코드를 복사해서 접속했는데 같은 에러가 발생합니다.

콘솔창에 뜬 에러 메세지는 다음과 같습니다. 

POST https://pre-onboarding-selection-task.shop/auth/signin net::ERR_NAME_NOT_RESOLVED

제 집에서 포스트맨으로 요청을 보냈을때는 정상적으로 작동하는거 같던데 해당 에러가 제 코드에 문제가 있는걸지 확인한번 

부탁드려도 괜찮을까요?

**Comment by younuk23** [comment]
요청을 보내는 주소가 잘못된 것으로 보이네요,

<https://pre-onboarding-selection-task.shop/>는 이전 도메인입니다. 현재 도메인은 <https://www.pre-onboarding-selection-task.shop/>입니다. 도메인네임 앞에 www 붙이신 후에 다시 요청을 보내면 정상동작할 것으로 보입니다.

또 문제있으면 문의주세요 :)
