### ISSUE TITLE
토큰을 못받고 있는데, 혹시 서버가 닫힌건가요?

### ISSUE THREAD

**Issue by Plu457** [walking-sunset/selection-task#58]
![image](https://user-images.githubusercontent.com/53371165/230776164-15198dd0-f19b-4e2a-841e-cae1a29e645d.png)
![image](https://user-images.githubusercontent.com/53371165/230776192-604adb15-23db-4276-8bef-8211a412cc9d.png)
![image](https://user-images.githubusercontent.com/53371165/230776212-8909cf19-88f4-435d-b9c7-076fffbc91d7.png)

**Comment by younuk23** [comment]
현재 서버는 정상동작하고 있는 것으로 보입니다. 스크린샷에서도 200 응답을 정상적으로 받은 것으로 보입니다.

지원자님이 구동하시는 환경과 연관된 오류로 예측됩니다. 서버에 관련된 오류가 아니기에 제 측에서 해결해드리기는 어려우며, 브라우저와도 연관이 있을 수 있으니 관련해서 에러메세지를 기반으로 여러 정보들 찾아보시고 해결하는 방향으로 진행해보는 것이 좋을 것 같습니다.
