### ISSUE TITLE
사용 가능 라이브러리 문의입니다.

### ISSUE THREAD

**Issue by ggsno** [walking-sunset/selection-task#6]
안녕하세요!
서버 데이터 관리를 위해 react-query 라이브러리 사용 가능할까요?

**Comment by walking-sunset** [comment]
안녕하세요 :)
react-query 라이브러리는 데이터 페칭, 캐싱, 스테이트 관리 등 기능과 직접적으로 연관된 부분이 있다고 판단되므로 사용을 지양해주시길 바랍니다!
