### ISSUE TITLE
로그인, 회원가입 경로 관련 질문드립니다.

### ISSUE THREAD

**Issue by Han-Na-05-22** [walking-sunset/selection-task#60]
로그인은 /signin 경로, 회원가입은 /signup 경로로 접근 가능하게 구현해야 한다고 적혀있는데요~

Login 컴포넌트 하나로 url 값에 따라 회원가입 or 로그인 화면이 보여지게 구현했는데 이렇게 해도 되는건가요~?

아니면 로그인, 회원가입 각각 따로 페이지를 만들어야 하나요??

**Comment by walking-sunset** [comment]
안녕하세요, 컴포넌트가 동일하더라도 /signin URL, /signup URL에 따라서 다른 화면이 보여지게 구성을 하셨다면, 이미 각자 따로 페이지가 만들어진 상태이신 것 같습니다. 따라서 URL값에 따라서 회원가입, 로그인 화면이 보여지고 각자 각 페이지의 요구사항에 맞게 동작하신다면 요구사항을 충족하신 것이 맞습니다
