### ISSUE TITLE
userId 관련

### ISSUE THREAD

**Issue by LJS0000** [walking-sunset/selection-task#61]
토큰에 email 만 있고 userID가 없습니다.
closed issue에서 비슷한 사례를 찾았는데 
혹시 서버측 에러인지 확인할 수 있을까요?

토큰
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6IjJAQCIsInN1YiI6ODg0NywiaWF0IjoxNjgxMzk2ODM0LCJleHAiOjE2ODIwMDE2MzR9.mbjQBJydcyGdjP1K4eiFD16F0XCD76-vSeqxLXsg8t4

**Comment by younuk23** [comment]
안녕하세요, 제공해주신 토큰에 userID에 대한 정보도 정상적으로 포함되어 있는 것으로 확인됩니다.
