### ISSUE TITLE
API 주소 문의

### ISSUE THREAD

**Issue by SSY1203** [walking-sunset/selection-task#69]
![image](https://github.com/walking-sunset/selection-task/assets/48400229/683d629f-c956-43e7-93a3-4e3c1556908a)
url에 오타는 없는 거 같고... headers와 data는 안에 규격대로 작성했는데
![image](https://github.com/walking-sunset/selection-task/assets/48400229/003fdf48-1f52-4287-92ef-8c4f75fe155e)
이렇게 뜹니다ㅠ 혹시 이메일과 비밀번호 입력했던 거 또 치면 안되는 건가요? 한번 눌렀을 때 201이 떴었는데 모르고 새로고침 해버렸는데 그 뒤로 위와 같은 에러가 뜨고, 혹시나 해서 다른 이메일과 비밀번호를 입력헀는데도 그대로인데 혹시 API 주소에 문제가 있나 문의드립니다!

**Comment by younuk23** [comment]
안녕하세요, 400 에러 응답을 정상적으로 받으신걸로 봐서 API는 정상 동작하고 있는 것으로 보입니다. 400은 요청하신 입력값이 잘못된 경우 발생하므로 입력값에 이상이 없는지 확인해보시면 좋을 것 같네요, 리스폰 메세지에도 참고할만한 내용이 있을거에요
