### ISSUE TITLE
로그인 하지 않고, /todo 접속 시, 코드 처리

### ISSUE THREAD

**Issue by hanseungjune** [walking-sunset/selection-task#71]
안녕하세요.

해당 제목대로 진행할 때도,
/SignIn 로 리다이렉트 해야되는거 아닌지 여쭙고 싶습시다.

감사합니다.

**Comment by younuk23** [comment]
네 요구조건에 있는대로 로그인되지 않은 상태에서 접속하려고 하면 /signin으로 리다이렉트해주시면 됩니다.

경로는 대소문자를 구분하니 유의하시길 바랍니다 :)
