### ISSUE TITLE
`input`의 `type`은 자유롭게 사용할 수 있을까요?

### ISSUE THREAD

**Issue by scarf005** [walking-sunset/selection-task#72]
https://github.com/walking-sunset/selection-task#-1-로그인--회원가입 에서, 예시에는 input의 `type`이 명시가 되어있지 않는데,
```html
<input data-testid="email-input" />
<input data-testid="password-input" />
<button data-testid="signup-button">회원가입</button>
```

data-testid만 충족된다면 type을 자유롭게 정해도 될까요? 예를 들어, `<input type="email" data-testid="email-input">` 대신 `<input type="text" data-testid="email-input">`으로 해도 되는지 궁금합니다.

**Comment by walking-sunset** [comment]
안녕하세요, 네 체크박스 등 완전히 다른 형식의 타입이 아니라 텍스트가 입력가능한 타입이라면 사용 가능합니다 :)
