### ISSUE TITLE
라이브러리 관련 

### ISSUE THREAD

**Issue by Donghyun-git** [walking-sunset/selection-task#73]
안녕하세요! 

jsonwebtoken 라이브러리 사용 가능할까요? 토큰 디코드 해서 로그인 정보 헤더에 띄워 주고 싶어서요!

**Comment by younuk23** [comment]
네, 핵심 기능과 연관되지 않았기에 사용해도 무방할 것으로 판단되네요, 사용하셔도 됩니다 :)
