### ISSUE TITLE
test파일 관련해 질문드립니다.

### ISSUE THREAD

**Issue by YeongseoYoon** [walking-sunset/selection-task#74]
App.test.tsx 파일과
setupTests.ts
파일을 삭제해 진행했는데, 혹시 이 파일들의 삭제가 과제 평가에 영향이 있을까요? 가이드에는 해당 내용이 기재되어 있지 않지만 혹시나 싶어 질문드립니다.

**Comment by younuk23** [comment]
test 관련 파일들은 삭제해도 됩니다. data-testid 속성만 정확하게 부여해주시면 됩니다 :)
