### ISSUE TITLE
디펜던시 및 사용법 질문드립니다.

### ISSUE THREAD

**Issue by zpxlffjrm** [walking-sunset/selection-task#75]
1. [MUI](https://mui.com/)을 사용해도 괜찮을까요?
2. MUI가 허용 된다면 아래 사항은 가이드를 위반한 경우 인가요?
  요구사항: TODO의 완료 여부는 `<input type="checkbox" />`를 통해 표현해주세요
  작성된 코드: 
   ```js
   ...
   <FormControlLabel
        control={
          <Checkbox
            checked={todo.isCompleted}
    ...

   ```

**Comment by yeonuk-hwang** [comment]
- MUI는 UI관련 라이브러리기에 사용 가능합니다.
- 해당 코드가 최종적으로 `<input type="checkbox" />` 형태의 HTML tag로 변환된다면 무방합니다.
