### ISSUE TITLE
"Assignment 7" 기능 구현 관련 질문드립니다.

### ISSUE THREAD

**Issue by huijunam** [walking-sunset/selection-task#77]
Assignment 7
TODO의 체크박스를 통해 완료 여부를 수정할 수 있도록 해주세요.

이 부분에서 완료 여부를 수정할 수 있도록 구현하는 게 어떤 의미인지 조금 설명을 부탁드려도 될까요?

**Comment by younuk23** [comment]
안녕하세요, 예시 GIF와 같이 체크박스의 체크, 체크해제를 통해서 완료 여부를 수정 가능하게 구현하라는 의미입니다.
어떤 부분이 헷갈리는지 구체적으로 말씀해주시면 좀 더 상세히 답변드릴 수 있습니다 :)

**Comment by huijunam** [comment]
완료 여부를 수정가능하게 라는것이 코드 상에서 isCompleted 와 연관이 있는건가요? 수정을 했을때 그 부분도 업데이트를 하라는 말씀이신건지 궁금합니다

**Comment by younuk23** [comment]
네, 완료 여부 수정이라는 것은 데이터의 완료 여부(isCompleted)가 수정이 되고, 그것이 UI에도 반영되는 것을 의미합니다.
