### ISSUE TITLE
사용가능한 라이브러리에 대해서 질문드립니다.

### ISSUE THREAD

**Issue by richcollector** [walking-sunset/selection-task#79]
기능에 직접적으로 영향을 미치는 라이브러리 라는 것에대한 자세한 설명 부탁드릴 수 있을까요?!

**Comment by younuk23** [comment]
기능에 직접적인 영향이 없는 라이브러리의 경우 예를 들어 dotenv가 있습니다. 해당 라이브러리는 기능 구현을 하는 데 아무런 영향을 미치지 않으며, 단지 환경변수만을 설정합니다.

기능에 직접적으로 영향을 미치는 라이브러리의 예시는 react-query가 있습니다. 해당 라이브러리는 API 호출 결과를 상태값으로 관리하고, 캐싱해주는 기능을 제공하기에 과제의 요구사항을 구현하는 데 직접적인 영향을 미칩니다. 또 다른 예시로는 react-hook-form이 있습니다. 해당 라이브러리는 input이 포함된 form의 관리를 도와주는 기능을 포함하고 있기에 기능에 영향을 미친다고 판단할 수 있습니다.
