### ISSUE TITLE
환경변수 .env 사용에 관하여

### ISSUE THREAD

**Issue by hwinkr** [walking-sunset/selection-task#83]
api 요청을 하는 BASE_URL을 `.env` 파일 내부에 환경변수로 관리하고 있고 gitignore에 `.env`파일을 추가 해서 깃허브에 올리지 않도록 했습니다. 
배포를 하고 제출 후, 멘토님들께서 실제로 코드를 실행시켰을 때 멘토님들 실행환경에서는 제가 설정한 환경변수가 없으므로 api호출과정에서 에러가 발생할 것 같은데, 이런 경우에는 BASE_URL을 환경변수로 관리하지 않아야 할까요?

**Comment by younuk23** [comment]
네, 가이드에서 말씀드린 것처럼 별도의 환경변수 세팅 없이 바로 실행할 수 있도록 설정해주세요 :)
