### ISSUE TITLE
가산점 관련 질문

### ISSUE THREAD

**Issue by llbllhllk** [walking-sunset/selection-task#84]
사전 선발과제의 가산점 기준이 커밋시간 기준이라고 들었습니다.
이력서 제출은 아직 안하고 어제 자정까지 커밋해놨으면 이력서 제출을 그 후에 보내도
사전 선발과제의 가산점을 받을 수 있는지 궁긍합니다.

**Comment by younuk23** [comment]
> 제출시기 가산점은 모집 페이지에서 제출한 시기와, 레파지토리의 default branch의 최종 커밋 시기를 기반으로 결정됩니다.
- 모집 페이지의 제출 시기와, 커밋 시기 모두 가산점 기준 시간에 충족해야 됩니다.
