### ISSUE TITLE
React.StrictMode에 관한 질문

### ISSUE THREAD

**Issue by hwinkr** [walking-sunset/selection-task#86]
로그인이 안되어 있는 상태에서 `/todo`로 이동하면, alert창을 띄우고 로그인창으로 리다이렉션을 하도록 코드를 구성했습니다.  
하지만, cra로 제일 처음 리액트 환경이 설정 됐을 때 `index.tsx`에 있는 `React.StrictMode`로 인해서 컴포넌트가 2번 호출이 돼서 alert창도 두번 렌더링이 되는 문제가 발생합니다.
배포 환경에서는 상관 없겠지만, 멘토님들의 로컬 환경에서 실행 했을 때 alert가 두번 렌더링이 될텐데 이게 감점 요인이 될까요?  
아니면 `React.StrictMode`를 주석처리 한 상태에서 제출을 해도 될까요??

**Comment by yeonuk-hwang** [comment]
질문하신 "StrictMode로 인한 alert 창이 두번 출력되고 리다이렉트가 이루어지는 부분"은 별도의 감점 요인이 되지 않기에 그대로 진행하셔도 됩니다 :)
