### ISSUE TITLE
API 통신 질문입니다.

### ISSUE THREAD

**Issue by Wjyeop** [walking-sunset/selection-task#87]
과제를 이 레파지토리를 그대로 가져와서 위에 작업을 해야 되는 건가요?
아님 그냥 제가 설정한 url이 잘못된 것인지 모르겠습니다.
![image](https://github.com/walking-sunset/selection-task/assets/80335539/d5669cc6-ac83-4ea2-a171-cbf56f886a58)
![image](https://github.com/walking-sunset/selection-task/assets/80335539/80b96556-710f-419f-b584-00e27ededa3a)

**Comment by yeonuk-hwang** [comment]
400에러를 응답받은 것으로 봤을 때, API 통신은 정상적으로 하고 있으신 걸로 보입니다. 통신을 통해서 얻은 status code와, payload, response를 통해서 오류를 어떻게 해결할 지 파악하고 진행하시면 될 것 같네요 :)
