### ISSUE TITLE
KT AIVLE 원티드랩 프리온보딩 사전과제 제출 오류 관련

### ISSUE THREAD

**Issue by YTH5503** [walking-sunset/selection-task#89]
![오류](https://github.com/walking-sunset/selection-task/assets/91369812/dfc8358e-c0ff-4fc7-ab13-a45acc882885)
안녕하세요 KT AIVLE 원티드랩 프리온보딩 frontend 지원자 윤태후 입니다.
주말부터 사전과제를 제출하려고 하나 제출하기 버튼이 클릭되지 않는 상황입니다. 이에 이 부분이 가산점에 영향을 끼칠지 여쭤보고 싶습니다.
감사합니다.

**Comment by yeonuk-hwang** [comment]
안녕하세요, 원티드 확인 결과 현재 제출이 되지 않는 문제는 해결되었다고 합니다. 추가적으로 모집 페이지를 포함한 운영상의 질문이 있을 경우 learning@wantedlab.com로 문의주시면 됩니다.

그리고, 이번 KT AIVLE 스쿨 프리온보딩 과정은 제출시기에 따른 별도의 가산점이 주어지지 않습니다 :)
