### ISSUE TITLE
gh-pages 배포 시 "Mixed-Contents"오류

### ISSUE THREAD

**Issue by Chaedie** [walking-sunset/selection-task#9]
##  "Mixed-Contents"오류
안녕하세요,
TodoApp 완성 이후 Github-Pages 통해 배포 하였는데, "Mixed-Contents"오류가 발생하네요. 

해결을 위해 아래 3가지 방법을 사용해봤는데, 해결이 안되어 이슈사항으로 문의드립니다.
<br/>

## 에러 해결을 위한 3가지 시도
1. baseUrl을 단순히 https로 변경해보았지만, API응답이 없음
2. @package.json에서 "homepage"를 https => http로 변경해보았으나, github page 기본 설정이 https인지 http로 배포가 안됨
3. (스택오버플로우 참고)   index.html에 `<meta
      http-equiv="Content-Security-Policy"
      content="upgrade-insecure-requests"
    />` 해당 코드 추가 해 보았으나 에러 현상 동일

## 이슈 요청
- 따라서, 혹시 위 방식 이외에 해결 가능한 방법이 있는지? 또는 서버 측에서 해당 이슈 해결이 가능한지 질문드려요~!!!
<br/> <br/>
 
## 에러 메시지 및 이미지
```
AuthForm.js:42 Mixed Content: The page at 
'https://chaedie.github.io/wanted-pre-onboarding-fe-7/' 
was loaded over HTTPS, 
but requested an insecure resource
 'http://ec2-3-38-135-202.ap-northeast-2.compute.amazonaws.com:8000/auth/signin'. 
This request has been blocked; 
the content must be served over HTTPS.
```

![image](https://user-images.githubusercontent.com/88099590/193615067-33f81e2c-36a4-45a1-94e0-3840d6289907.png)

**Comment by younuk23** [comment]
안녕하세요:) 배포 도메인 HTTPS 도메인으로 변경되었습니다. 이제 정상적으로 사용가능하실거에요
